/**
  disable loading animations to instantly load your website
  other animations will still work
**/
export const DISABLE_LOADING_PORTRAIT_ANIMATION = true;
export const DISABLE_LOADING_ANIMATION = false;

export const BLUR_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAFCAYAAAB8ZH1oAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA2ElEQVR4nAHNADL/AK2loBJ4aF9PbFtTenJeVqR4ZF5oj3Vre5N6bl+TeW1dno2FIG1tbQEAkoaBHHNhWGVvY2CcdGpsxX1/jZSVkJegnJqfjaKbnH2hpaw5ssraCACVem05a1VKimdiZsxocILqc4usyYqYr8+Tnq3GoKaxqZulsl2pusgYAItyZT5ZS0SOVmBv2k5skPdcibrwbY2x8HeKnvCFkZ7CgIqWcqWyvR8AiHJlPVFHRI5MXXPbQWmW+U+Du/Zafqb2XW6A9mhwesRmaW9ym6GnIJ8HZpSsqAUZAAAAAElFTkSuQmCC';
